### ISSUE TITLE
How to add own mesh object

### ISSUE THREAD

**Issue by prajwalresearch** [jhavl/swift#17]
Hi newbie here, I working with robotic toolbox with swift as backend I wanted to ask few things.
1.Where does the mesh files of objects are defined ? Like for sphere , box .
2. Is it possible to disable collision between two added objects like two spheres , box?
2.Is it possible to add own mesh/URDF objects in robotic toolbox +swift? 
Any help is appreciated.
Thank you .

**Comment by prarobinson** [comment]
I've had success adding my own robot and accompanying meshes by mimicing the included examples. Collada/.dae files will be in rtb-data/rtbdata/xacro/[robot] _description/meshes/visual, and the xacro files will be under rtb-data/rtbdata/xacro/[robot] _description/robots. You'll also need to create a new [robot].py file in roboticstoolbox/models/URDF.

I don't know about adding arbitrary geometry, but would like to! Must be an easier way than creating a URDF for a cube or other primitive.
