### ISSUE TITLE
Recording with Swift freezes

### ISSUE THREAD

**Issue by prajwalresearch** [jhavl/swift#19]
Hi, I was trying to record swift visualization
these were the general step

`env = swift.Swift()

env.launch()

panda = rtb.models.Panda()

env.add(panda)

env.start_recording( filename  , framerate=1/dt , "vis.gif")

for q in  trajectories:

    panda.q[:n] = q[:n]
    
    env.step(dt)
    
    time.sleep(0.02)
    
env.stop_recording()
`

I use constant dt in range of 0.01 to 0.07
Issues is simulation doesn't run on web, its just freeze at initial position , without recording option its run fine.
Is there any known issues regarding this  , is the general steps are correct ? 
using in ubuntu 20.04
Thanks

**Comment by prajwalresearch** [comment]
solved after the latest update.

**Comment by nicholasEspinal** [comment]
I am still seeing this same error, using 1.0.1. any advice?
