### ISSUE TITLE
Remove object by ID

### ISSUE THREAD

**Issue by VinceDT** [jhavl/swift#3]
Hey, 
thanks for the nice work. I wanted to remove a mesh that I added, but the functionality to remove by id seems not implemented yet. This is currently a critical point for me. Any plans on implementing that in the near future?
Best

**Comment by jhavl** [comment]
This functionality has just been added. You will also need to pull the latest changes in https://github.com/petercorke/robotics-toolbox-python. You can now remove by id or by object for example
