### ISSUE TITLE
Reference to nonexistent folder

### ISSUE THREAD

**Issue by adv4ncr** [jhavl/swift#7]
Hi @jhavl,

just checked out the new changes. Swift won't launch and I discovered a potential bug:

https://github.com/jhavl/swift/blob/1d7078f75dd8c9ff9164f573307220cd6cc8011c/swift/SwiftRoute.py#L148

Is `out` supposed to be a new public folder?
Because changing it to the current public by `root_dir = Path(sw.__file__).parent / 'public'` gives me a 404.

Regards and happy eastern 😀

**Comment by jhavl** [comment]
Thanks, you too :smile:
I have just done a massive rewrite of Swift! It seems as though the new file structure wasn't pushed to Github cleanly.

**Comment by jhavl** [comment]
Should be fixed now. The .gitignore was ignoring the out folder. The out directory is the new location of the 'public' folder for the front-end, public will be removed shortly.

**Comment by adv4ncr** [comment]
very nice, works now! Great job with the updated Swift!!
Maybe the new `spatialgeometry` package should be mentioned in the readme.
And rendering/capturing the simulator with the button crashes it for me, its under development I guess 😊

**Comment by jhavl** [comment]
@adv4ncr, can you please let me know if the crashing on rendering button is fixed with the latest commit?
