### ISSUE TITLE
Swift elements bug

### ISSUE THREAD

**Issue by adv4ncr** [jhavl/swift#8]
Hi @jhavl,
I have a simulation running with several buttons, one slider, checkboxes and radio buttons.
When setting the slider, the button element above is clicked.
When setting the radio button, the slider above is reset.
No issues here with the 'old' Swift.

Any ideas on that?

**Comment by jhavl** [comment]
I'll check it out, probably something to do with the new state management messing up

**Comment by jhavl** [comment]
Hey @adv4ncr, check out the latest commit and let me know if everything is working as expected
