### ISSUE TITLE
No tab opens when running on Mac

### ISSUE THREAD

**Issue by Daniella1** [jhavl/swift#9]
I have used the framework for visualizing a robot, using the robotics-toolbox-python library from petercorke. The visualization works in Windows, where a tab opens and the robot is visualized properly (see gif and robot_viz.txt (attached as txt instead of py file for git compatibility).
When running with the exact same version (roboticstoolbox-python==0.7.0) on a Mac, no tab opens. The Mac version used to test this was: catalina version 10.15.7

![swift_robot](https://user-images.githubusercontent.com/14126328/117135417-337e7000-ada7-11eb-8f5a-0b8e0866b46d.gif)

[robot_viz.txt](https://github.com/jhavl/swift/files/6426764/robot_viz.txt)

**Comment by Daniella1** [comment]
Update: the same code was tested on a MacOS (version: Mojave 10.14.6) and it worked. So it seems the issue may be only on Catalina for now.

**Comment by jhavl** [comment]
That is odd. Perhaps reinstalling the toolbox and swift fixed some underlying issue
